# This is a basic workflow to help you get started with Actions

name: Code check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: smelly-python/smell-my-pr@main
        with: 
          github-token: ${{secrets.GIT_TOKEN}}
          command: pipenv run smelly-python -d src
